name: Build Docker Image

on:
  push:
    branches:
      - main

  pull_request:

env:
  IS_RELEASE: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-tags: true

      - uses: FranzDiebold/github-env-vars-action@v2.1.0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto SemVer
        if: ${{ env.IS_RELEASE == 'true' }}
        id: get-ver
        uses: fregante/daily-version-action@v2.1.1

      # Build and Push Images
      - name: Build and Push Images
        run: |
          docker buildx bake --file docker-bake.hcl \
            --set runner.tags=${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.get-ver.outputs.version }} \
            --push

      - name: Create Release
        if: steps.get-ver.outputs.created
        uses: ncipollo/release-action@v1.11.1
        with:
          name: ${{ env.CI_REPOSITORY_NAME_SLUG }}-${{ steps.get-ver.outputs.version }}
          commit: ${{ github.sha }}
          tag: ${{ steps.get-ver.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: ${{ env.IS_RELEASE == 'false' }}